cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart, name='mycart'),
]

fahadcoffeeshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mycoffee.urls', namespace="mycoffee"))
    url(r'^cart/', include('cart.urls', namespace="cart")),
]

mycoffee/urls.py
from django.conf.urls import url
from . import views


app_name="mycoffee"

urlpatterns = [
	url(r'^signup/$', views.usersignup, name="signup"),
	url(r'^login/$', views.userlogin, name="login"),
	url(r'^logout/$', views.userlogout, name="logout"),
	url(r'^create_coffee/$', views.create_coffee, name='create_coffee'),
	url(r'^ajax_price/$', views.ajax_price, name="ajax_price"),
	url(r'^$', views.coffee_list, name='coffee_list'),
	url(r'^coffee_detail/(?P<coffee_id>[0-9]+)/$', views.coffee_detail, name="coffee_detail"),


]

mycoffee/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django.db.models.signals import pre_save, post_save, post_delete


class Bean(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=3)

    def __str__(self):
        return self.name


class Roast(models.Model):
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=5, decimal_places=3)

    def __str__(self):
        return self.name


class Syrup(models.Model):
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=5, decimal_places=3)

    def __str__(self):
        return self.name

class Powder(models.Model):
    name = models.CharField(max_length=150)
    price = models.DecimalField(max_digits=5, decimal_places=3)

class Coffee (models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    espresso_shots = models.PositiveIntegerField(default=1)
    bean = models.ForeignKey(Bean, on_delete=models.PROTECT)
    roast = models.ForeignKey(Roast, on_delete=models.PROTECT)
    syrups = models.ManyToManyField(Syrup, blank=True)
    powders = models.ManyToManyField(Powder, blank=True)
    water = models.FloatField()
    steamedmilk = models.BooleanField(default=False)
    foam = models.FloatField()
    extra_instructions = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=3, null = True)
        
    def __str__(self):
        return self.name


class CartItem(models.Model):
    cart = models.ForeignKey("Cart" ,on_delete=models.PROTECT)
    item = models.ForeignKey(Coffee, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    line_item_total = models.DecimalField(decimal_places = 3, max_digits = 20)
    def __str__(self):
        return self.item.title

def cart_item_pre_save_receiver(sender, instance, *args, **kwargs):
    qty = instance.quantity
    if qty>=1:
        price = instance.item.price
        line_item_total = Decimal(qty)*Decimal(price)
        instance.line_item_total = line_item_total

pre_save.connect(cart_item_pre_save_receiver, sender=CartItem)

def cart_item_post_save_receiver(sender, instance, *args, **kwargs):
    instance.cart.update_subtotal()

post_save.connect(cart_item_post_save_receiver, sender=CartItem)
post_delete.connect(cart_item_post_save_receiver, sender=CartItem)


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.PROTECT)
    items = models.ManyToManyField(Coffee, through=CartItem)
    subtotal = models.DecimalField(decimal_places = 3, max_digits = 50, default=2.000)
    delivery_total = models.DecimalField(decimal_places = 3, max_digits = 50, default=2.000)
    total = models.DecimalField(decimal_places = 3, max_digits = 50, default=2.000)

    def __str__(self):
        return str(self.id)



    def update_subtotal(self):
        subtotal = 0
        items = self.cartitem_set.all()
        for item in items:
            subtotal += items.line_items_total
        self.subtotal = "%.3f"%subtotal
        self.save()




def do_delivery_and_total(sender, instance, *args, **kwargs):
    subtotal = Decimal(instance.subtotal)
    delivery_total = Decimal(2.000)
    total = subtotal + delivery_total
    instance.delivery_total = "%.3f"%delivery_total
    instance.total = "%.3f"%total

pre_save.connect(do_delivery_and_total, sender=Cart)

mycoffee/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Coffee

class CoffeeForm(forms.ModelForm):
	class Meta:
		model = Coffee
		fields = "__all__"
		exclude = ['user', 'price']

class UserSignup(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'password']

		widgets = {

		'password': forms.PasswordInput(),
		}


class UserLogin (forms.ModelForm):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())

mycoffee/views.py
from django.shortcuts import render, redirect
from .forms import UserSignup, UserLogin
from django.contrib.auth import authenticate, login, logout
from .forms import CoffeeForm
from decimal import Decimal
from .models import Coffee
from django.http import Http404

def coffee_list(request):
	if not request.user.is_authenticated():
		return redirect("mycoffee:login")


	coffee_list = Coffee.objects.filter(user=request.user)
	return render(request, 'coffee_list.html', {'coffee_list':coffee_list})


def coffee_detail(request, coffee_id):
	if not request.user.is_authenticated():
		return redirect ("mycoffee:login")

	coffee = Coffee.objects.get(id=coffee_id)
	if not(request.user == coffee.user or request.user.is_superuser or request.user.us_staff):
		raise Http404

	return render(request, 'coffee_detail.html', {'coffee': coffee}) 


def usersignup(request):
	context = {}
	form = UserSignup()
	context['form'] = form
	if request.method == ' POST':
		form = UserSignup(request.POST)
		if form.is_valid():
			user = form.save()
			username = user.username
			password = user.password


			user.set_password(password)
			user.save()

			auth_user = authenticate(username=username, password=password )
			login(request, auth_user)

			return redirect("/")
		return redirect("mycoffee:signup")
	return render(request, 'signup.html', context)



def userlogin(request):
	context= {}
	form = UserLogin()
	context['form'] = form
	if request.method == 'POST':
		form = UserLogin(request.POST)
		if form.is_valid():
			
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			auth_user= authenticate(username=username, password=password)
			if auth_user is not None:
				login(request, auth_user)
				return redirect ('/')
			return redirect("mycoffee:login")
		return redirect ("mycoffee:login")
	return render (request, 'login.html', context)



def userlogout(request):
	logout(request)
	return redirect ("/")

def coffee_price(instance):
	total_price = instance.bean.price + instance.roast.price + (instance.espresso_shots*Decimal(0.250))
	if instance.steamed_milk:
		total_price+=Decimal(.100)
	if instance.powder.all().count()>0:
		for powder in instance.powders.all():
			total_price+=powder.price
	if instance.syrup.all().count()>0:
		for syrup in instance.syrups.all():
			total_price+=syrup.price
	return total_price


def create_coffee(request):
	context = {}
	if not request.user.is_authenticated():
		return redirect("mycoffee:login")
	form = CoffeeForm()
	if request_method == "POST":
		form = CoffeeForm(request.POST)
		if form.is_valid():
			coffee=form.save(commit=False)
			coffee.user = request.user
			coffee.save()
			form.save_m2m()
			coffee.price = coffee_price(coffee)
			coffee.save()
			return redirect('/')

	context['form'] = form
	return render (request, 'create_coffee.html', context)


def ajax_price(request):
	total_price = Decimal(0)

	bean_id = request.GET.get('bean')
	if bean_id:
		total_price += Bean.objects.get(id=bean_id).price

	roast_id = request.GET.get(roast)
	if roast_id:
		total_price += Roast.objects.get(id=roast_id).price

	syrups = json.loads(request.GET.get('syrups'))
	if len(syrups)>0:
		for syrup_id in syrups:
			total_price += syrup.objects.get(id=syrup_id).price


	powders = json.loads(request.GET.get('powders'))
	if len(powders)>0:
		for powder_id in powders:
			total_price += Powder.objects.get(id=powder_id).price

	milk = request.GET,get('milk')
	if milk=='true':
		total_price += Decimal(0.100)

	shots = request.GET.get('espresso_shots')
	if shots:
		total_price += (int(shots)*Decimal(0.250))


	return JsonResponse(rount(total_price,3), safe=False)

mycoffee/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Coffee Shop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

mycoffee/templates/coffee_detail.html
{% extends "base.html" %}

{% block content %}
<div class="row">
<div class="col-sm-12">
    <div class="thumbnail text-center">
        <div class="caption">
            <h3>{{coffee.name}}</h3>
            <p>Coffee Bean: {{coffee.bean}}</p>
            <p>Roast: {{coffee.roast}}</p>
            <p># of espresso shots: {{coffee.espresso_shots}}</p>
            <p>Water ammount: {{coffee.water}} ml.</p>
            <p>Steamed Milk: {% if coffee.steamed_milk %}Added {% else %}No Milk {% endif %}</p>
            <p>Foam: {{coffee.foam}} cm.</p>
            {% if coffee.syrup.all.count > 0 %}
                <p>Syrups Added: {% for syrup in coffee.syrups.all %} {{syrup.name}}{% endfor %}</p>
            {% endif %}
            {% if coffee.powder.all.count > 0 %}
                <p>Powders Added: {% for powder in coffee.powders.all %} {{powder.name}}{% endfor %}</p>
            {% endif %}
            <p>{{coffee.price}} KWD</p>
        </div>
    </div>
</div>
</div>
{% endblock content %}

mycoffee/templates/coffee_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        {% for coffee in coffee_list %}
        <div class="col-sm-4">
            <div class="thumbnail">
                <div class="caption text-center">
                    <h3>{{coffee.name}}</h3>
                    <p>{{coffee.price}} KWD</p>
                    <p><a href="{% url 'mycoffee:coffee_detail' coffee_id=coffee.id %}" class="btn btn-primary" role="button">More Details</a>
                    <p>
                        <form action="{% url 'cart:mycart' %}" method="GET">
                          <input type="hidden" name="item" value="{{coffee.id}}"/>
                          <input type="hidden" class="item-qty" name="qty" value="1"/>
                          <input type="submit" class="btn btn-success" value="Add to Cart"/>
                        </form>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

mycoffee/templates/create_coffee.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
	<form action="{url 'mycoffee:create' %}" method = "post">
		{% {% csrf_token %}
		{{forms|crispy}}
		

		<input class = "btn btn-primary" type="submit" value="Create Coffee">
	</form> 



<script> 
function update_price(){ 
	var bean = document.getElementById("id_bean");
	var bean_id = bean[bean.selectedIndex].value;
	console.log(bean_id);

	var roast = document.getElementById("id_roast");
	var roast_id = roast[roast.selectedIndex].value;
	console.log(roast_id);


	var espresso_shot = document.getElementById("id_espresso_shots");
	var espresso_shots_ammount = espresso_shots.value;
    console.log(espresso_shots_ammount); 


    var milk = document.getElementById('id_steamed_milk');
    var milk_value = milk.checked;
    console.log(milk_value);


    var powders = document.getElementById("id_powders");
    var selected_powders = [];
    for (var i = 0; i < powders.length; i++)
    {
        if (powders.options[i].selected)
            {
                selected_powders.push(powders.options[i].value);
            }
    }
    console.log(selected_powders);

$.ajax({
	type: 'GET',
	url: '{% url "mycoffee:ajax_price" %}',
	data: {
		bean: bean_id,
            roast: roast_id,
            espresso_shots: espresso_shots_ammount,
            milk: milk_value,
            powders: JSON.stringify(selected_powders),
            syrups: JSON.stringify(selected_syrups)
        },
    error: function() {
    	console.log('There was an error connecting');

    },
    sucess: function(data) {
    	console.log(data)
    }

}),


}
</script>

{% block content %}
    <form action="{% url 'mycoffee:create_coffee' %}" method="post" onchange="update_price()">
      {% csrf_token %}
      {{form|crispy}}

      <h3>Total:<span id="total">0.000</span> KWD</h3>
      <input class = "btn btn-primary" type="submit" value="Create Coffee">
    </form>
    
<script>
success: function(data) {
    document.getElementById('total').innerHTML=data;
   }

{% endblock %}

mycoffee/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'mycoffee:login' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Login">
    </form>
{% endblock content %}

mycoffee/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'mycoffee:signup' %}" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input class = "btn btn-primary" type="submit" value="Sign Up">
    </form>
{% endblock content %}